### ISSUE TITLE
yarn install错误

### ISSUE THREAD

**Issue by wzyhust2018** [fengli01/vue-bpmn-element#16]
yarn install时发生如下错误
warning element-ui > async-validator > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not re
commended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js vers
ions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual 
version of core-js.                                                                                                   
error Command failed.                                                                                                 
Exit code: 128                                                                                                        
Command: git

**Comment by fengli01** [comment]
改成npm了，再试试
