### ISSUE TITLE
npm  install  error

### ISSUE THREAD

**Issue by shaozhiqi** [fengli01/vue-bpmn-element#23]
![image](https://user-images.githubusercontent.com/19182371/157156621-afd7b3d9-2350-4e59-8bf0-c449a8e89599.png)

**Comment by BinK4ZHB** [comment]
升级一下git版本试试

**Comment by jiaoxiaorun** [comment]
我也是这个错误

**Comment by fengli01** [comment]
https://www.ipaddress.com/ 访问查询以下域名对应的IP，修改一下hosts试试
ip github.com
ip www.github.com
ip github.global.ssl.fastly.net
