### ISSUE TITLE
请问下作者，vue-bpmn的流程设计器的license是什么？

### ISSUE THREAD

**Issue by qixiaoxi7676** [fengli01/vue-bpmn-element#4]
请问下作者，vue-bpmn的流程设计器的license是什么？其他用户可以下载进行二次开发，然后商用么？

**Comment by fengli01** [comment]
开源的，基于bpmn.js开发，目前正在完善中，暂时没有考虑商用

**Comment by qixiaoxi7676** [comment]
Dear   fengli
您好 


也就是bpmn.js 流程设计器组件目前没有license，我这边可以下载进行二次开发使用？也可以商用是不？


Best regards

















在 2020-08-07 13:46:34，"fengli01" <notifications@github.com> 写道：

开源的，基于bpmn.js开发，目前正在完善中，暂时没有考虑商用

**Comment by fengli01** [comment]
可以的，目前盘古，jeeplus这两个工作流产品已经商用了，可以参考一下

**Comment by qixiaoxi7676** [comment]
Dear  fengli
谢谢 您 


我现在马上下载您的demo，使用下
best regards













在 2020-08-07 14:15:36，"fengli01" <notifications@github.com> 写道：

可以的，目前盘古，jeeplus这两个工作流产品已经商用了，可以参考一下

**Comment by fengli01** [comment]
参考盘古，jeeplus
